fix: fix a potential dos in the leaderboard command
thetayloredman/Lexi pull request #572
Opened 2022-07-28 19:34 UTC by thetayloredman

**Does this Pull Request fix an issue? If so, please mention the issue.**
N/A

**Describe your changes.**
This PR will add a new method of managing ECTs (emote counter/trackers) which is DOS-proof when a user spams the leaderboard or API.

**Additional context**
Entry from private triage (maintainers only link): https://canary.discord.com/channels/771056568988860433/970479855579828245/972633654843043890

2022-07-28 20:25 UTC, ilikestohack submitted a review, later dismissed
Looks alright I kinda got lost a bit but as long as it is tested it should be fine

2022-07-28 20:25 UTC, ilikestohack commented on src/lib/structures/LexiECTManager.ts
> +        for (const [id, count] of this[db]) {
Kinda questioning the output of id and count maybe I'm missing what they actually are?

2022-07-28 20:28 UTC, thetayloredman commented on src/lib/structures/LexiECTManager.ts
> +        for (const [id, count] of this[db]) {
id should be the user id
count is the number of entries

2022-07-28 20:31 UTC, thetayloredman reviewed
Forgot this lol

2022-07-28 21:20 UTC, ilikestohack requested changes
Explain the use of the still existant sort function

2022-07-28 21:20 UTC, ilikestohack commented on src/commands/leaderboard.ts
> +                sorted = client.emoteCounterTrackers.tildesArray().sort((a, b) => b[1] - a[1]);
But you are still sorting?

2022-07-28 21:20 UTC, ilikestohack commented on src/utils/web/index.ts
> +        } else res.json(client.emoteCounterTrackers.uwusArray().sort((a, b) => b[1] - a[1]));
Still sorting?

2022-07-28 21:20 UTC, ilikestohack commented on src/utils/web/index.ts
> +        } else res.json(client.emoteCounterTrackers.owosArray().sort((a, b) => b[1] - a[1]));
Still sorting?

2022-07-28 21:20 UTC, ilikestohack commented on src/utils/web/index.ts
> +        } else res.json(client.emoteCounterTrackers.tildesArray().sort((a, b) => b[1] - a[1]));
Still sorting?

2022-07-28 21:21 UTC, thetayloredman commented on src/commands/leaderboard.ts
> +                sorted = client.emoteCounterTrackers.tildesArray().sort((a, b) => b[1] - a[1]);
The leaderboard component isn't done yet so this is just the needed polyfill right now

2022-07-28 21:21 UTC, thetayloredman commented on src/utils/web/index.ts
> +        } else res.json(client.emoteCounterTrackers.uwusArray().sort((a, b) => b[1] - a[1]));
See previous comment

2022-07-28 21:21 UTC, thetayloredman commented on src/utils/web/index.ts
> +        } else res.json(client.emoteCounterTrackers.owosArray().sort((a, b) => b[1] - a[1]));
See previous comment

2022-07-28 21:22 UTC, thetayloredman commented on src/utils/web/index.ts
> +        } else res.json(client.emoteCounterTrackers.tildesArray().sort((a, b) => b[1] - a[1]));
See previous comment

2022-07-28 21:24 UTC, ilikestohack approved these changes
Comments were explained

2022-07-28 21:40 UTC, ilikestohack submitted a review, later dismissed
Looks good

2022-07-28 21:46 UTC, thetayloredman commented
From the test so far
![image](https://user-images.githubusercontent.com/26350849/181643030-a2840d90-89ed-4cd7-ad67-e45eebb71544.png)

2022-09-05 18:04 UTC, thetayloredman commented
Requires updates after #585 is merged

2022-09-05 19:34 UTC, 808-Dev commented
Clarified JS analysis with submitter.

2022-09-05 19:40 UTC, 808-Dev submitted a review, later dismissed
Reviewed and everything seems fine from here.

2022-09-23 16:13 UTC, thetayloredman commented
@808-Dev @ilikestohack complete, review please?

2022-09-25 21:21 UTC, ilikestohack approved these changes
Didn't trace down everything but it looks alright

2022-10-15 01:33 UTC, thetayloredman commented
> Didn't trace down everything but it looks alright
@ilikestohack 
i'll do some last-minute tests then i think we're green light

2022-10-15 01:34 UTC, thetayloredman commented
WHOOPS

2022-10-28 20:04 UTC, 808-Dev approved these changes
As far as I know everything should be fine. Apologies for the wait

2022-11-24 16:19 UTC, thetayloredman commented
I need an approving review to merge

2022-11-26 19:13 UTC, ilikestohack approved these changes
Seems fine to me but I didn't look in detail

2022-11-26 21:23 UTC, merged